version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: aaxistest_db
      POSTGRES_USER: aaxistest_user
      POSTGRES_PASSWORD: aaxistest_password
    ports:
      - "8124:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8123:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
